name: Release
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build-assets:
    name: Build assets
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: |
          deno install --allow-scripts
          deno compile --allow-net --allow-ffi --allow-env --target ${{ matrix.target }} --output dist/cash-drawer-middleware-${{ matrix.target }} server.js
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: cash-drawer-middleware-${{ matrix.target }}
